global SCREEN_WIDTH, SCREEN_HEIGHT
global SCREEN_WINDOW
global HOST_IP_ADDRESS
global HOST_PORT
global IMAGE_ASSET_EMPTY_BLOCK
global IMAGE_ASSET_WALL_BLOCK
global IMAGE_ASSET_DOT
global IMAGE_ASSET_PLAYERS
global CANVAS_UNIT

# SHARED MEMORY
global PLAYER_ID
global PLAYERS
global CANVAS
global NUMBER_CONNECTIONS

# CLIENT MUTEX LOCKS
global MUTEX_PLAYER_ID
global MUTEX_PLAYERS
global MUTEX_CANVAS_CELLS
