# Size and associated
global BOARD_WIDTH, BOARD_HEIGHT
global BOARD_MARGIN
global SCREEN_WIDTH, SCREEN_HEIGHT
global SCREEN_WINDOW
global CANVAS_UNIT

global HOST_IP_ADDRESS
global HOST_PORT
global IMAGE_ASSET_EMPTY_BLOCK
global IMAGE_ASSET_WALL_BLOCK
global IMAGE_ASSET_DOT
global IMAGE_ASSET_PLAYERS


# used for in-game score display
global ICON_CROWN
global ICON_PACMAN_RED
global ICON_PACMAN_GREEN
global ICON_PACMAN_BLUE
global ICON_PACMAN_YELLOW
global ICON_PACMAN_SIZE
